all: 
	g++ -Wall -o example_pointers example_pointers.cpp
	g++ -Wall -o example_pointers_function example_pointers_function.cpp
	g++ -Wall -o example_array example_array.cpp
	g++ -Wall -o example_character_array example_character_array.cpp
	g++ -Wall -o example_arguments_main example_arguments_main.cpp
	g++ -Wall -o example_file_handling example_file_handling.cpp
	g++ -Wall -o example_output_error_stream example_output_error_stream.cpp
	g++ -Wall -o example_pointer_wrong example_pointer_wrong.cpp
clean:
	rm example_pointers example_pointers_function example_array example_character_array example_arguments_main example_file_handling out example_output_error_stream example_pointer_wrong
	
